version: '3.4'

services:
  hlservice.customer:
    environment:
      Surging_Server_Address: 0.0.0.0
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerDes: "客户管理微服务组件"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "1100:100"
      - "8080:8080"

  hlservice.identity:
    environment:
      Surging_Server_Address: 0.0.0.0
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerDes: "微服务集群身份认证与授权组件"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "1101:100"
      - "8081:8080"

  hlservice.order:
    environment:
      Surging_Server_Address: 0.0.0.0
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerDes: "订单微服务组件"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "1102:100"
      - "8082:8080"

  hlservice.product:
    environment:
      Surging_Server_Address: 0.0.0.0
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerDes: "产品管理微服务组件"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "1103:100"
      - "8083:8080"

  hlservice.schedule:
    environment:
      Surging_Server_Address: 0.0.0.0
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${SCHEDULE_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerDes: "任务调度微服务组件"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "1104:100"
      - "8084:8080"

  hlservice.stock:
    environment:
      Surging_Server_Address: 0.0.0.0
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerDes: "库存管理微服务组件"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "1105:100"
      - "8085:8080"

  hlservice.systemmanager:
    environment:
      Surging_Server_Address: 0.0.0.0
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerDes: "系统管理微服务组件"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "1106:100"
      - "8086:8080"

  hlservice.wsserver:
    environment:
      Surging_Server_Address: 0.0.0.0
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${WS_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerDes: "ws服务组件"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "1107:100"
      - "196:96"